### ISSUE TITLE
Add UseDeveloperExceptionPage

### ISSUE THREAD

**Issue by nojaf** [giraffe-fsharp/giraffe-template#10]
Consider using [UseDeveloperExceptionPage](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling) when running in `Development` instead of the default `UseGiraffeErrorHandler`.

**Comment by dustinmoris** [comment]
@nojaf Have a look at 26169f6 and let me know if you want me to change something, otherwise it's ready to release.

**Comment by nojaf** [comment]
Wow, super quick! That's what I had in mind indeed. Merge away, thanks Dustin.
