### ISSUE TITLE
paket.bootstrapper.exe SSL/TLS error and workaround

### ISSUE THREAD

**Issue by PrsPrsBK** [giraffe-fsharp/giraffe-template#12]
Hi. I encountered error about paket.exe (in fact paket.bootstrapper.exe).
I did following operations on pwsh.exe, Windows10.

```
$ dotnet new giraffe -lang F# --UsePaket -o fooproj
$ cd fooproj
$ dotnet build src/fooproj
```
And error message.
Japanese part is maybe 'The request was aborted: Could not create SSL/TLS secure channel'.
>  要求は中止されました: SSL/TLS のセキュリティで保護されているチャネルを作成できませんでした (Github - cached (temporarily ignore updates))

# Work around

Simply download latest paket.bootstrapper.exe from [fsprojects/Paket](https://github.com/fsprojects/Paket) and rename to 'paket.exe' and replace.
This is maybe the result of [Github blog: Weak cryptographic standards removed](https://blog.github.com/2018-02-23-weak-cryptographic-standards-removed/).
Thanks.

**Comment by dustinmoris** [comment]
Thanks for the help, I'll try to get that updated today!

**Comment by dustinmoris** [comment]
The 0.17.0 release has the latest paket.bootstrapper.exe (named as paket.exe). Thanks for reporting again!

**Comment by JduPreez** [comment]
Awesome! this worked for me.
