### ISSUE TITLE
Paket.exe and build.sh issues in issues in giraffe template 0.17.0

### ISSUE THREAD

**Issue by sidkshatriya** [giraffe-fsharp/giraffe-template#18]
- When I try to do `sh build.sh` I get the following error:
```
$ sh build.sh 
build.sh: 8: build.sh: Syntax error: end of file unexpected (expecting "then")
```

- There still seems to be an issue with the paket.exe provided when using the `-U` flag 
```
$ mono .paket/paket.exe 
Error: SecureChannelFailure (The authentication or decryption has failed.) (Github - cached (temporarily ignore updates))
```

I believe you tried to address this in https://github.com/giraffe-fsharp/giraffe-template/issues/12 but that doesn't seem to have fixed the issue for me.  I have tried to re-install the template using `dotnet new -i "giraffe-template::0.17.0"` but that does not seem to have helped either.

When I replace `packet.exe` with the version I have explicitly downloaded from the paket github repo, things work fine.

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by magnushammar** [comment]
The cause is that build.sh has CRLF end of line instead of LF. The quick fix is that you change it manually.

**Comment by sidkshatriya** [comment]
@magnushammar Thank you! What about second issue (paket.exe SecureChannelFailure ) ?

**Comment by magnushammar** [comment]
I had no problem with that, but I didn't install that specific version of the template. I just happened to have a fresh Ubuntu 18.04 on my "TV" and I installed the template like this. `dotnet new -i "giraffe-template::*"`

Edit:  Now I am a bit confused cz the template package I have installed is `giraffe-template.0.17.0.nupkg` so I don't see what could be wrong. I am on the same OS and .Net core version (my mono is `5.12.0.226` but that shouldn't matter).

**Comment by sidkshatriya** [comment]
I am using the ubuntu 18.04 package manager (`apt`) installed `mono`.

```
$ mono --version
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

**Comment by sidkshatriya** [comment]
Try installing a fresh 18.04 installation and you may be able to repeat the error?

**Comment by magnushammar** [comment]
Downgraded to your version and got your error. I don't have time (going :biking_man:) to dig into the why now, but perhaps you can try to install a newer mono from mono-project.com and see if it gets you going?

**Comment by sidkshatriya** [comment]
I'm not blocked on anything -- I simply replaced packet.exe (bootstrapper) bundled by the giraffe template with the paket.exe from the github packet project and got going. 

Interestingly, when I try to use `packet.bootstrapper.exe` (which I downloaded myself from the paket project) I get:
```
 mono paket.bootstrapper.exe 
Checking Paket version (downloading latest stable)...
'Github - cached' download failed. If using Mono, you may need to import trusted certificates using the 'mozroots' tool as none are contained by default. Trying fallback download from 'Nuget - cached'.
Checking Paket version (downloading latest stable)...
Version 5.174.5 not found in cache.
Starting download from https://www.nuget.org/api/v2/package/Paket/5.174.5
```
_(Did a Ctrl+C)_
```
Bootstrapper cancelled
```

So it seems this is an issue with the `paket.bootstrapper.exe` the paket github project is making available for download. My certificates are synced via `cert-sync` so I wonder why its asking for `moztools` to be run...

**Comment by sidkshatriya** [comment]
Also, FYI I updated my mono to

```
mono --version
Mono JIT compiler version 5.12.0.226 (tarball Thu May  3 09:42:09 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

And the `paket.bootstrapper.exe` started working properly.  https://github.com/giraffe-fsharp/giraffe-template/issues/12#issue-308011502 seems to hint this could be due to github deprecations. 

When I updated my mono, I got a new ubuntu package of `ca-certificates-mono` so that might have helped with the ability to establish a secure and trusted connection to github. 

Anyways, all is well. Would be useful to know why exactly the older version of mono was giving problems but thats more academic a question. Thanks for the help!
