### ISSUE TITLE
Giraffe Template fails in post-build action to make scripts executable

### ISSUE THREAD

**Issue by BrutalSimplicity** [giraffe-fsharp/giraffe-template#23]
This is not a big issue but is a bit strange so I thought I'd create an issue.

When running `dotnet new giraffe -lang f# -n ProjectName` I'm successfully able to create the project, but the template fails in the post-action when attempting to make the build scripts executable. It appears that whatever script is executing the template install is treating the `chmod` arguments as separate commands.

```
Processing post-creation actions...
The files /Users/tabork/Development/fsharp/FirstGiraffeWebApp/chmod, /Users/tabork/Development/fsharp/FirstGiraffeWebApp/+x, and /Users/tabork/Development/fsharp/FirstGiraffeWebApp/*.sh do not exist.
Unable to apply permissions +x to "*.sh".
Post action failed.
Description: Make scripts executable
Manual instructions: Run 'chmod +x *.sh'
```

This is occurring on Mac OSX, with Dotnet SDK 2.1.4 installed.

Please let me know if you need additional information.

**Comment by TheAngryByrd** [comment]
This is a [known issue](https://github.com/dotnet/templating/issues/1028) with the dotnet sdk and they constant break this functionality.  The steps to fix this are listed in the output 

```
Manual instructions: Run 'chmod +x *.sh'
```

**Comment by vilinski** [comment]
Don't know whether it is the same:

1. What means `open: invalid option -- c` ?

<details><summary>output of `dotnet new giraffe`</summary>

```
Die Vorlage "Giraffe Web App" wurde erfolgreich installiert.

Aktionen nach der Erstellung werden verarbeitet...
open: invalid option -- c
Usage: open [-e] [-t] [-f] [-W] [-R] [-n] [-g] [-h] [-s <partial SDK name>][-b <bundle identifier>] [-a <application>] [filenames] [--args arguments]
Help: Open opens files from a shell.
      By default, opens each file using the default application for that file.
      If the file is in the form of a URL, the file will be opened as a URL.
Options:
      -a                Opens with the specified application.
      -b                Opens with the specified application bundle identifier.
      -e                Opens with TextEdit.
      -t                Opens with default text editor.
      -f                Reads input from standard input and opens with TextEdit.
      -F  --fresh       Launches the app fresh, that is, without restoring windows. Saved persistent state is lost, excluding Untitled documents.
      -R, --reveal      Selects in the Finder instead of opening.
      -W, --wait-apps   Blocks until the used applications are closed (even if they were already running).
          --args        All remaining arguments are passed in argv to the application's main() function instead of opened.
      -n, --new         Open a new instance of the application even if one is already running.
      -j, --hide        Launches the app hidden.
      -g, --background  Does not bring the application to the foreground.
      -h, --header      Searches header file locations for headers matching the given filenames, and opens them.
      -s                For -h, the SDK to use; if supplied, only SDKs whose names contain the argument value are searched.
                        Otherwise the highest versioned SDK in each platform is used.
Die Berechtigungen +x konnten nicht auf "*.sh" angewendet werden.
Fehler bei der nachfolgenden Aktion.
Beschreibung: Make scripts executable
Anweisungen: Run 'chmod +x *.sh'
```

</details>

---


2. And also `dotnet new giraffe` without parameters didn't create paket files, 
where `dotnet new giraffe --help` says the opposite:

```
Options:
...
  -U|--UsePaket
                     bool - Optional
                     Default: false / (*) true
```

**Comment by dustinmoris** [comment]
> open: invalid option -- c

Good question, will have to look into this.

> And also dotnet new giraffe without parameters didn't create paket files

This is the default setting. If you want to use Paket then you have to provide the `--UsePaket` flag:

```
dotnet new giraffe -o MyProject --UsePaket
```

**Comment by wiwiwa** [comment]
exactly the same issue

**Comment by dustinmoris** [comment]
Post build issue is working with the latest SDK and Giraffe template: https://www.nuget.org/packages/giraffe-template/1.0.0

The default for the Paket switch was always `false` and it was reported correctly in the output of `--help`:

```
Default: false / (*) true
```

It says `Default: false`, the `(*) true` is just displaying the other possible option and maybe the `(*)` is a weird way of showing this, but that has nothing to do with Giraffe but just how the .NET team designed their CLI.
