### ISSUE TITLE
The giraffe-template breaks the "implicit" contract of dotnet new templates

### ISSUE THREAD

**Issue by da9l** [giraffe-fsharp/giraffe-template#29]
Hi!

Mentioned in #6 but perhaps not fully expressed, the giraffe dotnet new template breaks the "implicit" contract that most dotnet new templates seems to fulfill regarding where the files are placed.

Background: 
I'm writing a script that is used to compose different dotnet new templates into a solution and I'm running into a problem with the giraffe template directory layout that I haven't seen with any other major dotnet new template.

I'd even go so far to say that the giraffe template breaks the "implicit" dotnet new template contract (I know it is an implicit/defacto/tacit contract but still) by adding the giraffe application into a pre-determined src folder.

All other dotnet new templates that creates a project (console, classlib, mstest, nunit, web, webapi etc) follow the contract that the project files are by default created in the current directory with the current directory name being used as the project name.

Templates following this contract make them composable into solutions, addable into existing solutions without imposing any kind of structure.

I'd claim that although the src folder pattern is good, the structure of any solution and source tree is a decision to be made by the developer setting it up and therefore a solution composition concern and not a template concern.

My understanding is that the need for this is having the option for the testproject option available. This is together with the paket option are composition concerns and should not be part of any specific template. If you want to distribute a test project that should go into it's own template in the package.

What one should be able to to do is something similar to:
```powershell
dotnet new classlib -lang f# -o model
dotnet new xunit -lang f# -o model.tests
dotnet new giraffe -o api
dotnet new giraffe.tests -o api.tests
dotnet sln add model
dotnet sln add model.tests
dotnet sln add api
dotnet sln add api.tests
```

Currently, if one run `dotnet new giraffe -o api` one will get this structure that makes no sense.
```
\---api
    \---src
        \---api
            \---WebRoot
```

**Comment by dustinmoris** [comment]
Thanks for reporting this issue. I agree with most of your explanation and therefore the default of the latest Giraffe template doesn't create a solution like structure anymore. Users who still want to create the solution style structure must use the new `--Solution` flag now.
