### ISSUE TITLE
`dotnet run` is completely quiet, does not show port

### ISSUE THREAD

**Issue by fbehrens** [giraffe-fsharp/giraffe-template#39]
Hi, thank you for reading this.

I was just getting started with Giraffe, and expected that the server will log to console under which port it will serve.

```
info: Microsoft.Hosting.Lifetime[0] Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0] Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0] Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0] Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0] Content root path: C:\Users\fb\OneDrive\code\schnelltest
```
but because of 
```fsharp
 builder.AddFilter(fun l -> l.Equals LogLevel.Error)
```
this was not displayed.

The server is completely silent, which took me some time to find out that it's running fine. 

My experience  would have been better, when then Information Log were shown, which I now suggest.

**Comment by dustinmoris** [comment]
Thanks for raising the issue! I've fixed it in the latest release today.
